apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-managed
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-managed
  template:
    metadata:
      labels:
        app: nginx-managed
    spec:
      containers:
      - name: nginx-managed
        image: nginx:1.14.2
        ports:
        - containerPort: 80
